spring:
  application:
    name: hotel-booking-system

  datasource:
    url: jdbc:sqlite:./data/hotel_booking.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    com.hotel: INFO